# Generated by Django 5.2.7 on 2025-11-19 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('event', 'order', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='EventVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(help_text="Role for this event, e.g. 'Main Decor', 'Photo & Video'.", max_length=255)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, help_text='Estimated vendor cost.', max_digits=12)),
                ('cost_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Actual final vendor cost.', max_digits=12, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('event', 'vendor__name'),
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('side', models.CharField(choices=[('bride', 'Bride Side'), ('groom', 'Groom Side'), ('both', 'Both Families'), ('other', 'Other')], default='both', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('invited', models.BooleanField(default=True)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('maybe', 'Maybe')], default='pending', max_length=16)),
                ('rsvp_count', models.PositiveIntegerField(default=1, help_text='Number of people included with this guest (e.g. +1).')),
                ('table_name', models.CharField(blank=True, help_text='Table name/number if applicable.', max_length=64)),
                ('is_vip', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('event', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('venue_type', models.CharField(choices=[('hotel', 'Hotel'), ('hall', 'Function Hall'), ('outdoor', 'Outdoor'), ('private_property', 'Private Property'), ('other', 'Other')], default='other', max_length=32)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, default='UAE', max_length=128)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Approximate maximum capacity.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('logistics', 'Logistics'), ('decor', 'Decor'), ('catering', 'Catering'), ('photography', 'Photography & Video'), ('program', 'Program & Rituals'), ('communication', 'Communication'), ('payments', 'Payments'), ('other', 'Other')], default='other', max_length=32)),
                ('is_done', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='services.vendor')),
            ],
            options={
                'ordering': ('event', 'due_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Internal event name, e.g. 'Rohan & Aisha – Wedding Ceremony'.", max_length=255)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('reception', 'Reception'), ('mehndi', 'Mehndi'), ('sangeet', 'Sangeet'), ('engagement', 'Engagement'), ('other', 'Other')], default='wedding', max_length=32)),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('planned', 'Planned'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32)),
                ('date', models.DateField(help_text='Main event date (for multi-day events, use earliest).')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('expected_guests', models.PositiveIntegerField(blank=True, help_text='Expected guest count.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.client')),
            ],
            options={
                'ordering': ('date', 'start_time', 'name'),
            },
        ),
    ]
