# Generated by Django 5.2.7 on 2025-11-20 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('other', 'Other / Family')], default='other', max_length=16)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number if different from phone.', max_length=32)),
                ('allow_marketing', models.BooleanField(default=True, help_text='Allow anniversary wishes, offers, and follow-up messages.')),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='events.event')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('event', 'role', 'full_name'),
                'unique_together': {('event', 'role')},
            },
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
