# Generated by Django 5.2.7 on 2025-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventperson_delete_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, default='INDIA', max_length=128),
        ),
    ]
