# Generated by Django 5.2.7 on 2025-12-03 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venue_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventperson',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='website',
        ),
        migrations.AddField(
            model_name='venue',
            name='district',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, default='Kerala', max_length=128),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='eventperson',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['bride', 'groom'])), fields=('event', 'role'), name='unique_bride_groom_per_event'),
        ),
    ]
