# Generated by Django 5.2.7 on 2025-12-04 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventperson_unique_together_remove_event_deal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventvendor',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
