# Generated by Django 5.2.7 on 2025-12-13 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_checklistitem_owner_alter_event_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnniversaryWishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversary_wish_logs', to='events.eventperson')),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('person', 'year'), name='uniq_anniversary_wish_per_person_year')],
            },
        ),
    ]
