# Generated by Django 5.2.7 on 2026-05-07 11:58
# events/migrations/0008_cleanup_old_event_models.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_anniversarywishlog"),
        ("services", "0001_initial"),
        ("projects", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        # 1. Remove constraints first
        migrations.RemoveConstraint(
            model_name="anniversarywishlog",
            name="uniq_anniversary_wish_per_person_year",
        ),
        migrations.RemoveConstraint(
            model_name="eventperson",
            name="unique_bride_groom_per_event",
        ),

        # 2. Delete old models directly
        migrations.DeleteModel(
            name="AnniversaryWishLog",
        ),
        migrations.DeleteModel(
            name="EventPerson",
        ),
        migrations.DeleteModel(
            name="EventTimelineItem",
        ),
        migrations.DeleteModel(
            name="EventVendor",
        ),

        # 3. Remove old fields from existing models
        migrations.RemoveField(
            model_name="checklistitem",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="event",
            name="expected_guests",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="capacity",
        ),

        # 4. Add new Event fields
        migrations.AddField(
            model_name="event",
            name="client_template_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="client_template_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes for team/vendor preparation.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="vendor_template_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="vendor_template_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional for now. Can be made required later.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_events",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Services planned for this event.",
                related_name="events",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="packages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Packages planned for this event.",
                related_name="events",
                to="services.package",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="vendors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vendors/operators attached to this event.",
                related_name="events",
                to="services.vendor",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="inventory_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Company assets planned for this event.",
                related_name="events",
                to="services.inventoryitem",
            ),
        ),

        # 5. Add Venue is_active
        migrations.AddField(
            model_name="venue",
            name="is_active",
            field=models.BooleanField(default=True),
        ),

        # 6. Alter existing fields
        migrations.AlterField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional for now. Can be made required later.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="crm.client",
            ),
        ),

        # 7. New indexes
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(fields=["event", "is_done"], name="events_chec_event_i_780d4a_idx"),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(fields=["category"], name="events_chec_categor_e8da6e_idx"),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(fields=["due_date"], name="events_chec_due_dat_51078f_idx"),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(fields=["assigned_to"], name="events_chec_assigne_14f911_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="events_even_date_5e8e1c_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_even_status_5709b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["event_type"], name="events_even_event_t_a87b5c_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["client"], name="events_even_client__cb42cb_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["project"], name="events_even_project_1adb21_idx"),
        ),
    ]