# Generated by Django 5.2.7 on 2026-05-07 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_cleanup_old_event_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ('event', 'is_done', 'due_date', 'title')},
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='category',
            field=models.CharField(choices=[('event_setup', 'Event Setup'), ('service', 'Service'), ('package', 'Package'), ('vendor', 'Vendor'), ('inventory', 'Inventory'), ('venue', 'Venue'), ('communication', 'Communication'), ('internal', 'Internal'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('reception', 'Reception'), ('engagement', 'Engagement'), ('mehndi', 'Mehndi'), ('sangeet', 'Sangeet'), ('haldi', 'Haldi'), ('save_the_date', 'Save the Date'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('other', 'Other')], default='wedding', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Example: Shahin Wedding Photography Event', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Client-facing or general event notes.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('hall', 'Function Hall'), ('outdoor', 'Outdoor'), ('private_property', 'Private Property'), ('auditorium', 'Auditorium'), ('resort', 'Resort'), ('home', 'Home'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
