# Generated by Django 5.2.7 on 2026-05-07 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_checklistitem_options_and_more'),
        ('services', '0006_inventoryitem_category_inventoryitem_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('event__date', 'event__name'),
            },
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ('checklist', 'is_done', 'due_date', 'title')},
        ),
        migrations.RemoveIndex(
            model_name='checklistitem',
            name='events_chec_event_i_780d4a_idx',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, related_name='events', to='services.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='events', to='services.package'),
        ),
        migrations.AlterField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='events', to='services.service'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='events', to='services.vendor'),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_checklist', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventchecklist',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.eventchecklist'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['checklist', 'is_done'], name='events_chec_checkli_b3ba99_idx'),
        ),
    ]
