# Generated by Django 5.2.7 on 2025-11-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venue_country'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='delivery_medium',
            field=models.CharField(blank=True, help_text='e.g., Pendrive, Printed album, Photo book, Framed print.', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='file',
            field=models.FileField(blank=True, help_text='Optional file stored in your own storage.', null=True, upload_to='deliverables/'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='handed_over_to',
            field=models.CharField(blank=True, help_text='Name of person who received it (bride/groom/family).', max_length=255),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of physical items (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='type',
            field=models.CharField(choices=[('digital', 'Digital (online link)'), ('physical', 'Physical item'), ('mixed', 'Digital + Physical')], default='digital', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event this project is handling (wedding, reception, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='events.event'),
        ),
    ]
