# Generated by Django 5.2.7 on 2025-11-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_deliverable_delivery_medium_deliverable_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='tasks',
            field=models.ManyToManyField(blank=True, help_text='Tasks that produced this deliverable.', related_name='deliverables', to='projects.task'),
        ),
    ]
