# Generated by Django 5.2.7 on 2025-11-23 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_task_options_alter_deliverable_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='manager',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Manager or employee responsible for this deliverable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
