# Generated by Django 5.2.7 on 2025-11-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_deliverable_manager_deliverable_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
