# Generated by Django 5.2.7 on 2025-11-24 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_inquiry_owner_alter_client_country'),
        ('events', '0004_alter_venue_country'),
        ('projects', '0007_alter_deliverable_status'),
        ('sales', '0005_proposalitem_package_alter_proposalitem_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=64)),
                ('client_email', models.CharField(blank=True, max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('contract_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_numbers', models.TextField(blank=True, help_text='Comma-separated invoice numbers for this project.')),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payments_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='True when payments_total >= invoice_total.')),
                ('event_dates', models.TextField(blank=True, help_text='Comma-separated event dates (YYYY-MM-DD).')),
                ('event_venues', models.TextField(blank=True, help_text='Comma-separated venue names.')),
                ('deliverables_data', models.JSONField(blank=True, default=list, help_text='List of deliverables with name/type/status/file_link.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshots', to='crm.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshots', to='sales.contract')),
                ('main_event', models.ForeignKey(blank=True, help_text='Primary event for this project, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_event_snapshots', to='events.event')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
