# Generated by Django 5.2.7 on 2025-12-03 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectsnapshot'),
        ('sales', '0006_remove_deal_currency_remove_deal_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='directory',
            field=models.CharField(blank=True, default='', help_text='Folder path or directory for source files (optional).', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.CharField(blank=True, help_text="File count or brief notes (e.g., '1500 RAW photos', '3 reels').", max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='directory',
            field=models.CharField(blank=True, default='', help_text='Folder path or directory for source files (optional).', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('mixed', 'Image + Video'), ('other', 'Other')], default='image', help_text='Main file type handled in this task.', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this deliverable was marked delivered.', null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description or notes for this deliverable.'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Target date for delivering this item.', null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='name',
            field=models.CharField(help_text="Name of deliverable (e.g., 'Edited Wedding Photos', 'Highlight Film').", max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical item'), ('mixed', 'Digital + Physical')], default='digital', help_text='Whether this deliverable is digital, physical, or mixed.', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='Linked sales deal (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sales.deal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Internal notes or summary of what this project covers.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, help_text='Target completion date for this project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Planned start date for this project.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the task was marked completed.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed instructions or notes for this task.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Target date for completing this task.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text="Short name for the task (e.g., 'Culling – Haldi Photos').", max_length=255),
        ),
    ]
