# Generated by Django 5.2.7 on 2025-12-04 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_deliverable_owner_alter_project_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='first_started_at',
            field=models.DateTimeField(blank=True, help_text='When this deliverable was first moved from Pending to In Progress.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='first_started_at',
            field=models.DateTimeField(blank=True, help_text='When this task was first moved from Pending to In Progress.', null=True),
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True, help_text='When the user started working (status -> IN_PROGRESS).')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, help_text='When the user stopped working (status left IN_PROGRESS).', null=True)),
                ('deliverable', models.ForeignKey(blank=True, help_text='If this work session is for a Deliverable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='projects.deliverable')),
                ('owner', models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text='If this work session is for a Task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('task__isnull', False), ('deliverable__isnull', True)), models.Q(('task__isnull', True), ('deliverable__isnull', False)), _connector='OR'), name='worklog_single_target'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='worklog_one_active_per_user')],
            },
        ),
    ]
