# Generated by Django 5.2.7 on 2025-12-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_deliverable_first_started_at_task_first_started_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSnapshot',
        ),
    ]
