# Generated by Django 5.2.7 on 2026-05-06 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_inquiry_wedding_city_inquiry_wedding_country_and_more'),
        ('events', '0007_anniversarywishlog'),
        ('projects', '0012_delete_projectsnapshot'),
        ('sales', '0010_alter_deal_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_resumed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('work_seconds', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['due_date', 'status', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['sort_order', 'due_date', 'status', 'priority', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='deliverable',
            name='projects_de_status_690c02_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='projects_ta_status_d6b74c_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='projects_ta_priorit_dd6c2d_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='category',
            field=models.CharField(choices=[('album', 'Album'), ('poster', 'Poster'), ('save_the_date', 'Save the Date'), ('promo_video', 'Promo Video'), ('reel', 'Video Reel'), ('highlight_film', 'Highlight Film'), ('full_film', 'Full Wedding Film'), ('photo_set', 'Edited Photo Set'), ('other', 'Other')], db_index=True, default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='department',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('design', 'Design'), ('album', 'Album'), ('mixed', 'Mixed'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='preview_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='ready_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('import', 'Import'), ('selection', 'Selection / Culling'), ('editing', 'Editing'), ('color', 'Color / Grading'), ('audio', 'Audio / Sync'), ('design', 'Design'), ('export', 'Export'), ('qc', 'Quality Check'), ('delivery_support', 'Delivery Support'), ('other', 'Other')], db_index=True, default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('design', 'Design'), ('album', 'Album'), ('mixed', 'Mixed'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional estimated time in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='delivery_medium',
            field=models.CharField(blank=True, help_text='Google Drive, WhatsApp, Pendrive, Printed Album, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='directory',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='deliverables/'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='file_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='first_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='handed_over_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_for_tasks', 'Waiting for Tasks'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('internal_review', 'Internal Review'), ('client_review', 'Client Review'), ('revision_requested', 'Revision Requested'), ('ready_to_deliver', 'Ready to Deliver'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='tasks',
            field=models.ManyToManyField(blank=True, help_text='Tasks required before this deliverable can start/deliver.', related_name='deliverables', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('mixed', 'Digital + Physical')], db_index=True, default='digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional at first. Can be linked later.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='Optional linked deal. Can be linked later.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sales.deal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional linked wedding/event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='events.event'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Project Manager responsible for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='count',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='directory',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='first_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('review', 'Review'), ('revision', 'Revision'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['project', 'status'], name='projects_de_project_a80bde_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['assigned_to', 'status'], name='projects_de_assigne_6c147a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['department', 'category'], name='projects_de_departm_b6ef36_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['type', 'status'], name='projects_de_type_51986d_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['delivered_at'], name='projects_de_deliver_f4657d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['completed_at'], name='projects_pr_complet_5f4dda_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager', 'status'], name='projects_pr_manager_9c148a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='projects_ta_project_cd2085_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='projects_ta_assigne_6bc973_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department', 'category'], name='projects_ta_departm_d1b7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed_at'], name='projects_ta_complet_8de8aa_idx'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='projects.deliverable'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='projects.task'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_work_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WorkLog',
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['user', 'status'], name='projects_wo_user_id_112aac_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['project', 'status'], name='projects_wo_project_37671b_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['task', 'status'], name='projects_wo_task_id_3756be_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['deliverable', 'status'], name='projects_wo_deliver_a8c5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['started_at'], name='projects_wo_started_a7b4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['ended_at'], name='projects_wo_ended_a_6d4c46_idx'),
        ),

    ]
