# Generated by Django 5.2.7 on 2026-05-06 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_worksession_remove_worklog_deliverable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task__isnull', False), ('deliverable__isnull', True)), models.Q(('task__isnull', True), ('deliverable__isnull', False)), _connector='OR'), name='worksession_single_target'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_worksession_per_user'),
        ),
    ]
