# Generated by Django 5.2.7 on 2026-05-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_worksession_worksession_single_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_directory',
            field=models.CharField(blank=True, default='', help_text='Main folder or drive path for this project.', max_length=500),
        ),
    ]
