# Generated by Django 5.2.7 on 2026-05-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_deliverable_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', 'status', 'priority', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='sort_order',
        ),
    ]
