# Generated by Django 5.2.7 on 2026-05-16 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_task_options_remove_task_sort_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['start_date', 'due_date', 'status', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['start_date', 'due_date', 'status', 'priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='deliverable',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('closed', 'Closed / Payment Collected'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=30),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['start_date'], name='projects_de_start_d_de6f91_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['start_date'], name='projects_ta_start_d_068621_idx'),
        ),
    ]
