# Generated by Django 5.2.7 on 2025-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_document_related_client_document_related_deal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Wedding CRM', max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('default_currency', models.CharField(default='AED', max_length=10)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=50)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('allow_self_registration', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
