# Generated by Django 5.2.7 on 2025-12-04 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_notification'),
        ('crm', '0005_alter_client_owner_alter_contact_owner_and_more'),
        ('events', '0006_alter_checklistitem_owner_alter_event_owner_and_more'),
        ('sales', '0007_alter_contract_owner_alter_deal_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['type', 'value'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Communication', 'verbose_name_plural': 'Communications'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='type',
            field=models.CharField(db_index=True, help_text="Machine key for the group of choices, e.g. 'lead_source', 'vendor_type'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(help_text="Human-readable value shown in dropdown, e.g. 'Instagram'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='communication',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('call', 'Phone Call')], help_text='Medium used for this communication.', max_length=20),
        ),
        migrations.AlterField(
            model_name='communication',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client this communication is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Specific contact person (bride, groom, etc.) involved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Lead this communication is tied to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='message',
            field=models.TextField(blank=True, help_text='Full message body or call summary.'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communication',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who sent or logged this communication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communication',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject or short summary of the communication.', max_length=255),
        ),
        migrations.AlterField(
            model_name='communication',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this communication was sent or took place.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes about this document.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Uploaded file (PDF, image, etc.).', upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_client',
            field=models.ForeignKey(blank=True, help_text='Client this document is primarily related to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_deal',
            field=models.ForeignKey(blank=True, help_text='Deal/booking this document is related to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.deal'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_event',
            field=models.ForeignKey(blank=True, help_text='Event this document is related to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='events.event'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='Short title for this document.', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who triggered this notification, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Marked as read once user sees/acknowledges it.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, help_text='Human-readable notification text.', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('project_assigned', 'Project assigned'), ('task_assigned', 'Task assigned'), ('overdue', 'Overdue'), ('deliverable_overdue', 'Deliverable overdue')], help_text='Type/category of this notification.', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User who will see this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='allow_self_registration',
            field=models.BooleanField(default=False, help_text='Allow new users to sign up themselves.'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='company_name',
            field=models.CharField(blank=True, help_text='Your business/legal entity name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='default_currency',
            field=models.CharField(default='AED', help_text='Default currency code (e.g. AED, INR, USD).', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='site_name',
            field=models.CharField(default='Wedding CRM', help_text='Name shown in the header/title of the site.', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Support or contact email shown to users.', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='timezone',
            field=models.CharField(default='Asia/Dubai', help_text='Default timezone string for the app.', max_length=50),
        ),
    ]
