# Generated by Django 5.2.7 on 2025-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('crm', 'CRM / Clients'), ('sales', 'Sales / Deals'), ('events', 'Events / Venues'), ('projects', 'Projects / Tasks'), ('ui', 'UI / Design'), ('billing', 'Billing / Payments')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optional screenshot (PNG/JPG).', null=True, upload_to='ticket_screenshots/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject_type',
            field=models.CharField(choices=[('bug', 'Bug / Error'), ('feature', 'Feature Request'), ('howto', 'How-to Question'), ('data_issue', 'Data Issue'), ('performance', 'Slow / Performance'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
