# Generated by Django 5.2.7 on 2025-12-05 18:55

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_ticket_category_ticket_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Human-friendly ticket number.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optional screenshot (PNG/JPG).', null=True, upload_to=common.models.ticket_screenshot_upload_to),
        ),
    ]
