# Generated by Django 5.2.7 on 2026-05-06 08:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_ticket_ticket_number_alter_ticket_screenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('login_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('logout', 'Manual Logout'), ('auto_timeout', 'Auto Timeout'), ('system', 'System'), ('unknown', 'Unknown')], db_index=True, default='', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['user', 'login_at'], name='common_user_user_id_36d82a_idx'), models.Index(fields=['user', 'logout_at'], name='common_user_user_id_5379c6_idx'), models.Index(fields=['session_key'], name='common_user_session_70bc6c_idx'), models.Index(fields=['logout_at', 'end_reason'], name='common_user_logout__786190_idx')],
            },
        ),
    ]
