# Generated by Django 5.2.7 on 2026-05-06 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_userloginsession'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, help_text='Prevents the same notification being created repeatedly.', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('inquiry_assigned', 'Inquiry assigned'), ('lead_follow_up', 'Lead follow-up'), ('deal_expected_close', 'Deal expected close'), ('proposal_due', 'Proposal due'), ('contract_ending', 'Contract ending'), ('invoice_due', 'Invoice due'), ('project_assigned', 'Project assigned'), ('project_due', 'Project due'), ('project_completed_review_pending', 'Project completed - review pending'), ('task_assigned', 'Task assigned'), ('task_due', 'Task due'), ('deliverable_assigned', 'Deliverable assigned'), ('deliverable_due', 'Deliverable due'), ('event_reminder', 'Event reminder')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='common_noti_recipie_ec1f06_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notif_type', 'created_at'], name='common_noti_notif_t_f1785b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['dedupe_key'], name='common_noti_dedupe__64b25a_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False), models.Q(('dedupe_key', ''), _negated=True)), fields=('recipient', 'dedupe_key'), name='unique_notification_per_recipient_dedupe_key'),
        ),
    ]
