# Generated by Django 5.2.7 on 2026-05-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_notification_options_notification_dedupe_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
