# Generated by Django 5.2.7 on 2026-05-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_delete_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
