# Generated by Django 5.2.7 on 2026-08-09 17:13

import django.db.models.deletion
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models


def backfill_session_expiry(apps, schema_editor):
    UserLoginSession = apps.get_model("common", "UserLoginSession")
    database = schema_editor.connection.alias
    for login_session in UserLoginSession.objects.using(database).filter(
        expires_at__isnull=True,
    ).iterator():
        login_session.expires_at = login_session.login_at + timedelta(hours=16)
        login_session.save(using=database, update_fields=["expires_at"])


def clear_session_expiry(apps, schema_editor):
    UserLoginSession = apps.get_model("common", "UserLoginSession")
    UserLoginSession.objects.using(schema_editor.connection.alias).update(expires_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_userloginsession_single_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginsession',
            options={'ordering': ['-login_at'], 'permissions': [('review_attendance', 'Can review missing attendance checkouts')]},
        ),
        migrations.AddField(
            model_name='userloginsession',
            name='checkout_request_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userloginsession',
            name='checkout_review_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Missing Checkout'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='userloginsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_session_expiry, clear_session_expiry),
        migrations.AddField(
            model_name='userloginsession',
            name='requested_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userloginsession',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userloginsession',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userloginsession',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_checkout_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('logout', 'Manual Logout'), ('auto_timeout', 'Auto Timeout'), ('session_expired', '16-hour Session Expired'), ('session_replaced', 'Replaced by New Login'), ('system', 'System'), ('unknown', 'Unknown')], db_index=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'permissions': [('review_leave_requests', 'Can review employee leave requests')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_not_before_start')],
            },
        ),
    ]
