# Generated by Django 5.2.7 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_importantnotice_usernoticeacknowledgement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloginsession",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("logout", "Manual Logout"),
                    ("auto_timeout", "Auto Timeout"),
                    ("session_expired", "Fixed Session Expired"),
                    ("session_replaced", "Replaced by New Login"),
                    ("system", "System"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="",
                max_length=30,
            ),
        ),
    ]
