# Generated by Django 5.2.7 on 2026-05-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Wedding CRM', help_text='Name shown in the header/title of the site.', max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Your business/legal entity name.', max_length=200)),
                ('default_currency', models.CharField(default='AED', help_text='Default currency code (e.g. AED, INR, USD).', max_length=10)),
                ('timezone', models.CharField(default='Asia/Dubai', help_text='Default timezone string for the app.', max_length=50)),
                ('support_email', models.EmailField(blank=True, help_text='Support or contact email shown to users.', max_length=254)),
                ('allow_self_registration', models.BooleanField(default=False, help_text='Allow new users to sign up themselves.')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
