# Generated by Django 5.2.7 on 2026-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='company_name',
            field=models.CharField(default='Ocean Clouds', help_text='Your business/legal entity name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='default_currency',
            field=models.CharField(default='INR', help_text='Default currency code (e.g. AED, INR, USD).', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='site_name',
            field=models.CharField(default='Wedding ERP', help_text='Name shown in the header/title of the site.', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='support_email',
            field=models.EmailField(default='help@oceanclouds.in', help_text='Support or contact email shown to users.', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='Default timezone string for the app.', max_length=50),
        ),
    ]
