# Generated by Django 5.2.7 on 2025-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, default='INDIA', max_length=128),
        ),
    ]
