# Generated by Django 5.2.7 on 2025-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_vendor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.CharField(default='IND', max_length=8),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final package selling price (auto-calculated from items).', max_digits=12),
        ),
    ]
