# Generated by Django 5.2.7 on 2025-12-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_package_currency_alter_package_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='service',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.AddField(
            model_name='vendor',
            name='district',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, default='Kerala', max_length=128),
        ),
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, help_text='Internal package code (auto-generated if left blank, e.g., PAC001).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, help_text='Internal service code (auto-generated if left blank, e.g., SER001).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=128),
        ),
    ]
