# Generated by Django 5.2.7 on 2026-05-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_inventoryitem_owner_alter_package_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('camera', 'Camera'), ('lens', 'Lens'), ('light', 'Light'), ('drone', 'Drone'), ('audio', 'Audio'), ('tripod', 'Tripod / Stand'), ('memory', 'Memory / Storage'), ('computer', 'Computer / Editing'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, help_text='Storage location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Linked service, if this item is usually used for that service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='services.service'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='pcs', help_text='Example: pcs, sets, units.', max_length=32),
        ),
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, help_text='Internal package code. Auto-generated if left blank, e.g., PAC001.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated from package items.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='description',
            field=models.CharField(help_text='Visible line description. Example: Wedding Photography - Full Day', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base selling price.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('photography', 'Photography'), ('videography', 'Videography'), ('drone', 'Drone'), ('album', 'Album / Printing'), ('editing', 'Editing / Post Production'), ('decor', 'Decor'), ('catering', 'Catering'), ('makeup', 'Makeup & Styling'), ('entertainment', 'Entertainment'), ('planning', 'Planning & Coordination'), ('venue', 'Venue'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, help_text='Internal service code. Auto-generated if left blank, e.g., SER001.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='vendors',
            field=models.ManyToManyField(blank=True, help_text='Preferred vendors/operators who can deliver this service.', related_name='services', to='services.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Primary contact, person name, or brand name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('videographer', 'Videographer'), ('drone_operator', 'Drone Operator'), ('editor', 'Editor'), ('album_vendor', 'Album / Printing Vendor'), ('decor', 'Decor Vendor'), ('caterer', 'Caterer'), ('makeup_artist', 'Makeup Artist'), ('music_band', 'Band / DJ / Entertainment'), ('venue', 'Venue Provider'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
