# Generated by Django 5.2.7 on 2026-05-26 16:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_inventoryitem_category_inventoryitem_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageitem',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AddField(
            model_name='packageitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='description',
            field=models.CharField(blank=True, help_text='Visible line description. Example: Wedding Photography - Full Day', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PackageDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(choices=[('item', 'Item'), ('hour', 'Hour'), ('day', 'Day'), ('photo', 'Photo'), ('video', 'Video'), ('album', 'Album'), ('page', 'Page'), ('minute', 'Minute'), ('other', 'Other')], default='item', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='services.package')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(choices=[('item', 'Item'), ('hour', 'Hour'), ('day', 'Day'), ('photo', 'Photo'), ('video', 'Video'), ('album', 'Album'), ('page', 'Page'), ('minute', 'Minute'), ('other', 'Other')], default='item', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='services.service')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
