"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import environ
import os
import logging

logging.getLogger("fontTools").setLevel(logging.ERROR)
logging.getLogger("weasyprint").setLevel(logging.ERROR)

# ------------------------------------------------------------------------------
# Paths & env
# ------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=(str, "change-me"),
    DJANGO_ALLOWED_HOSTS=(list, []),
    DJANGO_CSRF_TRUSTED_ORIGINS=(list, []),
    DJANGO_SECURE_SSL_REDIRECT=(bool, False),
    DJANGO_SESSION_COOKIE_SECURE=(bool, False),
    DJANGO_CSRF_COOKIE_SECURE=(bool, False),
    DB_ENGINE=(str, "sqlite"),
    DB_NAME=(str, "db.sqlite3"),
    DB_USER=(str, ""),
    DB_PASSWORD=(str, ""),
    DB_HOST=(str, ""),
    DB_PORT=(str, ""),
    DB_CONN_MAX_AGE=(int, 60),
    APP_VERSION=(str, "dev"),
    AWS_REGION=(str, ""),
    AWS_SES_SENDER=(str, ""),
    AWS_ACCESS_KEY_ID=(str, ""),
    AWS_SECRET_ACCESS_KEY=(str, ""),
    AWS_S3_ENABLED=(bool, False),
    AWS_STORAGE_BUCKET_NAME=(str, ""),
    AWS_S3_REGION_NAME=(str, "ap-south-1"),
    EMAIL_SENDING_ENABLED=(bool, True),
    EMAIL_DEFAULT_FROM=(str, ""),
    EMAIL_DEFAULT_REPLY_TO=(str, ""),

    WHATSAPP_SENDING_ENABLED=(bool, False),
    WHATSAPP_PROVIDER=(str, "meta"),  # meta or msg91

    META_WHATSAPP_ACCESS_TOKEN=(str, ""),
    META_WHATSAPP_PHONE_NUMBER_ID=(str, ""),
    META_WHATSAPP_BUSINESS_ACCOUNT_ID=(str, ""),
    META_WHATSAPP_API_VERSION=(str, "v22.0"),

    MSG91_AUTHKEY=(str, ""),
    MSG91_WHATSAPP_NAMESPACE=(str, ""),
    MSG91_WHATSAPP_INTEGRATED_NUMBER=(str, ""),
)
environ.Env.read_env(BASE_DIR / ".env")

DEBUG = env("DJANGO_DEBUG")
SECRET_KEY = env("DJANGO_SECRET_KEY")
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS")
SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT")
SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE")
CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
APP_VERSION = env("APP_VERSION")
AWS_REGION = env("AWS_REGION")
AWS_SES_SENDER = env("AWS_SES_SENDER")
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_S3_ENABLED = env.bool("AWS_S3_ENABLED")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME")
EMAIL_SENDING_ENABLED = env.bool("EMAIL_SENDING_ENABLED")
EMAIL_DEFAULT_FROM = env("EMAIL_DEFAULT_FROM") or AWS_SES_SENDER
EMAIL_DEFAULT_REPLY_TO = env("EMAIL_DEFAULT_REPLY_TO") or AWS_SES_SENDER
WHATSAPP_SENDING_ENABLED = env.bool("WHATSAPP_SENDING_ENABLED")
WHATSAPP_PROVIDER = env("WHATSAPP_PROVIDER")

META_WHATSAPP_ACCESS_TOKEN = env("META_WHATSAPP_ACCESS_TOKEN")
META_WHATSAPP_PHONE_NUMBER_ID = env("META_WHATSAPP_PHONE_NUMBER_ID")
META_WHATSAPP_BUSINESS_ACCOUNT_ID = env("META_WHATSAPP_BUSINESS_ACCOUNT_ID")
META_WHATSAPP_API_VERSION = env("META_WHATSAPP_API_VERSION")

MSG91_AUTHKEY = env("MSG91_AUTHKEY")
MSG91_WHATSAPP_NAMESPACE = env("MSG91_WHATSAPP_NAMESPACE")
MSG91_WHATSAPP_INTEGRATED_NUMBER = env("MSG91_WHATSAPP_INTEGRATED_NUMBER")

# ------------------------------------------------------------------------------
# Apps
# ------------------------------------------------------------------------------
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "django_crontab",
    "storages",
]


LOCAL_APPS = [
    "common.apps.CommonConfig",
    "crm.apps.CrmConfig",
    "sales.apps.SalesConfig",
    "adminpanel",
    "events",
    "services.apps.ServicesConfig",
    "messaging.apps.MessagingConfig",
    "projects.apps.ProjectsConfig",
    "reports",
    "todos.apps.TodosConfig",
    "ui",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ------------------------------------------------------------------------------
# Middleware / URLConf / WSGI
# ------------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "common.middleware.CloseExpiredLoginSessionsMiddleware",
    "common.middleware.ClearFrontendMessagesBeforeAdminMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"
WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"

# ------------------------------------------------------------------------------
# Templates (global templates live in ui/templates)
# ------------------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "ui" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "common.context_processors.notifications",
                "django.contrib.messages.context_processors.messages",
                "ui.context_processors.app_version",
            ],
        },
    },
]

# ------------------------------------------------------------------------------
# Database (SQLite by default; Postgres via .env)
# ------------------------------------------------------------------------------
DB_ENGINE = env("DB_ENGINE")

if DB_ENGINE == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST"),
            "PORT": env("DB_PORT"),
            "CONN_MAX_AGE": env.int("DB_CONN_MAX_AGE"),
            "CONN_HEALTH_CHECKS": True,
        }
    }
else:
    # sqlite fallback
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / env("DB_NAME"),
        }
    }

# ------------------------------------------------------------------------------
# Auth / i18n / tz
# ------------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------------------
# Static & Media
# ------------------------------------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "ui" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Uploaded files live under media/ locally. Individual FileField/ImageField
# upload_to values create their own subfolders inside this directory.
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# MEDIA: local by default, S3 in production if enabled
if AWS_S3_ENABLED:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    AWS_S3_REGION_NAME = AWS_S3_REGION_NAME
    AWS_STORAGE_BUCKET_NAME = AWS_STORAGE_BUCKET_NAME

    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False

    # If bucket stays private, URLs may not open directly in browser (still ok for uploads)
    AWS_QUERYSTRING_AUTH = False

    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"


# ------------------------------------------------------------------------------
# Logging (simple dev config)
# ------------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "loggers": {
        "fontTools": {"handlers": ["null"], "level": "ERROR"},
        "weasyprint": {"handlers": ["null"], "level": "ERROR"},
    },
    "handlers": {
        "null": {
            "class": "logging.NullHandler",
        }
    },
}

# ------------------------------------------------------------------------------
# Default primary key type
# ------------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "ui:login"

# ------------------------------------------------------------------------------
# Cron jobs (django-crontab)
# ------------------------------------------------------------------------------
# This will run your `notify_overdue` management command every day at midnight.
CRONJOBS = [
    ("0 0 * * *", "django.core.management.call_command", ["generate_due_todos"]),
]
#CRONJOBS = [
    #("0 0 * * *", "django.core.management.call_command", ["notify_due_items"]),
    #("0 0 * * *", "django.core.management.call_command", ["generate_due_todos"]),
#]

# Authentication expires after three hours without a completed request.
AUTO_LOGOUT_IDLE_SECONDS = 3 * 60 * 60
SESSION_COOKIE_AGE = AUTO_LOGOUT_IDLE_SECONDS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True      # reset inactivity timer
