"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import environ
import os
import logging

logging.getLogger("fontTools").setLevel(logging.ERROR)
logging.getLogger("weasyprint").setLevel(logging.ERROR)

# ------------------------------------------------------------------------------
# Paths & env
# ------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=(str, "change-me"),
    DJANGO_ALLOWED_HOSTS=(list, []),
    DB_ENGINE=(str, "sqlite"),
    DB_NAME=(str, "db.sqlite3"),
    DB_USER=(str, ""),
    DB_PASSWORD=(str, ""),
    DB_HOST=(str, ""),
    DB_PORT=(str, ""),
    APP_VERSION=(str, "dev"),
    AWS_REGION=(str, ""),
    AWS_SES_SENDER=(str, ""),
    AWS_ACCESS_KEY_ID=(str, ""),
    AWS_SECRET_ACCESS_KEY=(str, ""),
    AWS_S3_ENABLED=(bool, False),
    AWS_STORAGE_BUCKET_NAME=(str, ""),
    AWS_S3_REGION_NAME=(str, "ap-south-1"),
)
environ.Env.read_env(BASE_DIR / ".env")

DEBUG = env("DJANGO_DEBUG")
SECRET_KEY = env("DJANGO_SECRET_KEY")
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")
APP_VERSION = env("APP_VERSION")
AWS_REGION = env("AWS_REGION")
AWS_SES_SENDER = env("AWS_SES_SENDER")
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_S3_ENABLED = env.bool("AWS_S3_ENABLED")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME")

# ------------------------------------------------------------------------------
# Apps
# ------------------------------------------------------------------------------
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "django_crontab",
    "storages",
]


LOCAL_APPS = [
    "common",
    "crm",
    "sales",
    "events",
    "services",
    "messaging",
    "projects.apps.ProjectsConfig",
    "ui",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ------------------------------------------------------------------------------
# Middleware / URLConf / WSGI
# ------------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"
WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"

# ------------------------------------------------------------------------------
# Templates (global templates live in ui/templates)
# ------------------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "ui" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "common.context_processors.notifications",
                "django.contrib.messages.context_processors.messages",
                "ui.context_processors.app_version",
            ],
        },
    },
]

# ------------------------------------------------------------------------------
# Database (SQLite by default; Postgres via .env)
# ------------------------------------------------------------------------------
DB_ENGINE = env("DB_ENGINE")

if DB_ENGINE == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST"),
            "PORT": env("DB_PORT"),
        }
    }
else:
    # sqlite fallback
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / env("DB_NAME"),
        }
    }

# ------------------------------------------------------------------------------
# Auth / i18n / tz
# ------------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------------------
# Static & Media
# ------------------------------------------------------------------------------
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "ui" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# MEDIA: local by default, S3 in production if enabled
if AWS_S3_ENABLED:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    AWS_S3_REGION_NAME = AWS_S3_REGION_NAME
    AWS_STORAGE_BUCKET_NAME = AWS_STORAGE_BUCKET_NAME

    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False

    # If bucket stays private, URLs may not open directly in browser (still ok for uploads)
    AWS_QUERYSTRING_AUTH = False

    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"
else:
    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "media"


# ------------------------------------------------------------------------------
# Logging (simple dev config)
# ------------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "loggers": {
        "fontTools": {"handlers": ["null"], "level": "ERROR"},
        "weasyprint": {"handlers": ["null"], "level": "ERROR"},
    },
    "handlers": {
        "null": {
            "class": "logging.NullHandler",
        }
    },
}

# ------------------------------------------------------------------------------
# Default primary key type
# ------------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "ui:login"

# ------------------------------------------------------------------------------
# Cron jobs (django-crontab)
# ------------------------------------------------------------------------------
# This will run your `notify_overdue` management command every day at midnight.
CRONJOBS = [
    # minute hour day month weekday
    ("0 0 * * *", "django.core.management.call_command", ["notify_overdue"]),
]
"""CRONJOBS = [
    ("0 0 * * *", "django.core.management.call_command", ["notify_overdue"]),
    ("0 7 * * *", "django.core.management.call_command", ["send_anniversary_wishes"]),
]"""

SESSION_COOKIE_AGE = 10 * 60 * 60      # 8 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True     # reset inactivity timer