# Generated by Django 5.2.7 on 2026-05-09 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0011_inquiry_wedding_city_inquiry_wedding_country_and_more'),
        ('projects', '0017_alter_task_options_remove_task_sort_order'),
        ('sales', '0010_alter_deal_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='crm.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='sales.contract')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='sales.deal')),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='projects.deliverable')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='sales.invoice')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='crm.lead')),
                ('owner', models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='projects.project')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='sales.proposal')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='projects.task')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='todos_todo_assigne_54a7a5_idx'), models.Index(fields=['owner', 'status'], name='todos_todo_owner_i_ca6b5e_idx'), models.Index(fields=['status'], name='todos_todo_status_9f7c48_idx'), models.Index(fields=['priority'], name='todos_todo_priorit_93f987_idx'), models.Index(fields=['due_date'], name='todos_todo_due_dat_f2739d_idx'), models.Index(fields=['project', 'status'], name='todos_todo_project_39dd78_idx'), models.Index(fields=['client', 'status'], name='todos_todo_client__7ea161_idx'), models.Index(fields=['deal', 'status'], name='todos_todo_deal_id_8a31e7_idx')],
            },
        ),
    ]
