# Generated by Django 5.2.7 on 2026-05-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_inquiry_wedding_city_inquiry_wedding_country_and_more'),
        ('events', '0012_alter_checklistitem_checklist'),
        ('projects', '0017_alter_task_options_remove_task_sort_order'),
        ('sales', '0010_alter_deal_client'),
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='events.checklistitem'),
        ),
        migrations.AddField(
            model_name='todo',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['event', 'status'], name='todos_todo_event_i_c2e76c_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['checklist_item', 'status'], name='todos_todo_checkli_2b720e_idx'),
        ),
    ]
