# Generated by Django 5.2.7 on 2025-12-11 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('campaign', 'Campaign'), ('proposal', 'Proposal'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('anniversary', 'Anniversary')], default='campaign', help_text='Where this template is used.', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='HTML body. You can use Django template variables like {{ client.name }}, {{ deal.title }}, {{ event.date }}.')),
                ('body_text', models.TextField(blank=True, help_text='Optional plain-text version (for clients that do not support HTML).')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_for_type', models.BooleanField(default=False, help_text='If true, this will be used as the default template for this type (e.g. default proposal template).')),
                ('owner', models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('from_email', models.EmailField(blank=True, default='', help_text='Sender email. Defaults to AWS_SES_SENDER if left blank.', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('target_type', models.CharField(choices=[('custom_list', 'Custom email list'), ('clients', 'All active clients'), ('contacts', 'All active contacts'), ('leads', 'All open leads')], default='custom_list', help_text='Where to pull recipients from. For CUSTOM_LIST you will add recipients manually or via import.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='First day the cron job is allowed to send for this campaign.', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Preferred daily start time (e.g. 08:00).', null=True)),
                ('weekdays_only', models.BooleanField(default=True, help_text='If true, only run Monday–Friday.')),
                ('daily_limit', models.PositiveIntegerField(default=80, help_text='Maximum emails per day for this campaign.')),
                ('delay_seconds', models.PositiveIntegerField(default=5, help_text='Delay between individual sends (for SES reputation).')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(limit_choices_to={'type': 'campaign'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.campaign')),
            ],
            options={
                'ordering': ['campaign', 'email'],
                'unique_together': {('campaign', 'email')},
            },
        ),
    ]
