# Generated by Django 5.2.7 on 2025-12-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='custom_list_raw',
            field=models.TextField(blank=True, help_text='Used only when Target Type is Custom list. Enter one recipient per line as: Name, email@example.com (or just email@example.com).'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='daily_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='delay_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.EmailField(blank=True, default='noreply@oceanclouds.in', help_text='Sender email. Defaults to AWS_SES_SENDER if left blank.', max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='reply_to',
            field=models.EmailField(blank=True, default='help@oceanclouds.in', help_text='Reply-to email. Defaults to AWS_SES_SENDER if left blank.', max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_type',
            field=models.CharField(choices=[('custom_list', 'Custom list (paste recipients)'), ('client_marketing', 'Clients (contacts with allow marketing)')], default='custom_list', help_text='How recipients are selected for this campaign.', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='weekdays_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(help_text="Unique identifier used by the system and automation. Use lowercase letters, numbers and hyphens only (e.g. 'campaign-welcome').", unique=True),
        ),
    ]
