# Generated by Django 5.2.7 on 2025-12-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_checklistitem_owner_alter_event_owner_and_more'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipient',
            name='event_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='events.eventperson'),
        ),
    ]
