# Generated by Django 5.2.7 on 2026-05-07 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_campaign_custom_list_raw_alter_campaign_daily_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(blank=True, max_length=30)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('skipped', 'Skipped'), ('sent', 'Sent'), ('failed', 'Failed')], default='skipped', max_length=20)),
                ('ses_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Optional image, PDF, or file attached with this template.', upload_to='email_template_attachments/%Y/%m/')),
                ('display_name', models.CharField(blank=True, help_text='Optional file name shown in the email attachment.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['type', 'name']},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='custom_list_raw',
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='client_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='contact_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='attach_generated_pdf',
            field=models.BooleanField(default=False, help_text='If enabled, the related generated PDF will be attached when available.'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='pdf_attachment_mode',
            field=models.CharField(choices=[('none', 'No generated PDF'), ('related_object', 'Attach generated PDF from related record')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='daily_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_type',
            field=models.CharField(choices=[('client_marketing', 'Client contacts with allow marketing'), ('anniversary', 'Bride/Groom anniversary contacts')], default='client_marketing', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'type': 'campaign'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(help_text='HTML email body. You can use variables like {{ client.name }}, {{ proposal.title }}, {{ invoice.total_amount }}.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_text',
            field=models.TextField(blank=True, help_text='Optional plain text fallback.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active template is allowed for each type.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_default_for_type',
            field=models.BooleanField(default=True, help_text='Active template will be treated as the default for this type.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(help_text='Example: proposal-default, invoice-default, anniversary-wish', unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='Example: Proposal from {{ company_name }} - {{ proposal.title }}', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('campaign', 'Campaign'), ('proposal', 'Proposal'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('anniversary', 'Anniversary')], default='campaign', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('type',), name='only_one_active_email_template_per_type'),
        ),
        migrations.AddField(
            model_name='emailsendlog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='messaging.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emailtemplateattachment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.emailtemplate'),
        ),
    ]
