# Generated by Django 5.2.7 on 2026-05-07 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_emailsendlog_emailtemplateattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Example: event-client-default, event-vendor-default', unique=True)),
                ('type', models.CharField(choices=[('event_client', 'Event - Client'), ('event_vendor', 'Event - Vendor'), ('proposal', 'Proposal'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('anniversary', 'Anniversary'), ('custom', 'Custom')], default='event_client', max_length=40)),
                ('provider', models.CharField(choices=[('meta', 'Meta WhatsApp Cloud API'), ('msg91', 'MSG91')], default='meta', max_length=20)),
                ('provider_template_name', models.CharField(help_text='Exact approved template name in Meta/MSG91. Example: event_client_update', max_length=255)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('en_US', 'English US'), ('en_GB', 'English UK'), ('ml', 'Malayalam'), ('hi', 'Hindi')], default='en', help_text='Must match approved WhatsApp template language.', max_length=20)),
                ('category', models.CharField(choices=[('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=30)),
                ('body_text', models.TextField(help_text='Internal preview body. Use Django variables like {{ event.name }}, {{ client.name }}, {{ venue.name }}. This is for your preview/log only. Actual WhatsApp template text is approved in provider.')),
                ('header_text', models.CharField(blank=True, help_text='Optional internal preview header.', max_length=255)),
                ('footer_text', models.CharField(blank=True, help_text='Optional internal preview footer.', max_length=255)),
                ('variable_order', models.JSONField(blank=True, default=list, help_text='Ordered variables for WhatsApp template parameters. Example: ["event.name", "event.date", "venue.name"]')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_for_type', models.BooleanField(default=True, help_text='Only one active default WhatsApp template per type/provider/language.')),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(blank=True, max_length=40)),
                ('provider', models.CharField(choices=[('meta', 'Meta WhatsApp Cloud API'), ('msg91', 'MSG91')], default='meta', max_length=20)),
                ('to_number', models.CharField(max_length=32)),
                ('rendered_message', models.TextField(blank=True)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('skipped', 'Skipped'), ('sent', 'Sent'), ('failed', 'Failed')], default='skipped', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='messaging.whatsapptemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default_for_type', True)), fields=('type', 'provider', 'language_code'), name='only_one_active_whatsapp_template_per_type_provider_lang'),
        ),
    ]
