# Generated by Django 5.2.7 on 2026-05-07 18:16

import django.db.models.deletion
import messaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_whatsapptemplate_whatsappsendlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.PositiveIntegerField(blank=True, editable=False, help_text='Human-friendly ticket number.', null=True, unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('crm', 'CRM / Clients'), ('sales', 'Sales / Deals'), ('events', 'Events / Venues'), ('projects', 'Projects / Tasks'), ('ui', 'UI / Design'), ('billing', 'Billing / Payments')], default='general', max_length=20)),
                ('subject_type', models.CharField(choices=[('bug', 'Bug / Error'), ('feature', 'Feature Request'), ('howto', 'How-to Question'), ('data_issue', 'Data Issue'), ('performance', 'Slow / Performance'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot (PNG/JPG).', null=True, upload_to=messaging.models.ticket_screenshot_upload_to)),
                ('admin_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
