# Generated by Django 5.2.7 on 2025-11-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_detail',
            field=models.CharField(blank=True, help_text='Optional extra detail (e.g. referrer name, specific campaign, event name).', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('friend', 'Friend'), ('exhibition', 'Exhibition / Expo'), ('other', 'Other')], help_text='Where this lead came from (Website, Instagram, WhatsApp, Referral, Friend, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='wedding_country',
            field=models.CharField(blank=True, default='INDIA', max_length=100),
        ),
    ]
