# Generated by Django 5.2.7 on 2025-12-03 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_inquiry_owner_alter_client_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='client',
            name='alt_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='website',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, default='Kerala', max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='wedding_country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='wedding_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='wedding_state',
            field=models.CharField(blank=True, default='Kerala', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='wedding_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='wedding_state',
            field=models.CharField(blank=True, default='Kerala', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='display_name',
            field=models.CharField(blank=True, help_text="Optional shorter name used in UI (e.g. 'Anita & Rohan Wedding').", max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='channel',
            field=models.CharField(choices=[('website', 'Website Form'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('facebook', 'Facebook'), ('email', 'Email'), ('referral', 'Referral'), ('other', 'Other')], default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('friend', 'Friend'), ('exhibition', 'Exhibition / Expo'), ('other', 'Other')], help_text='Where this lead came from (Website, Instagram, WhatsApp, Referral, Friend, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='wedding_country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('client', 'email'), name='uniq_contact_email_per_client_non_empty'),
        ),
    ]
