# Generated by Django 5.2.7 on 2025-12-04 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_client_owner_alter_contact_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Overall rating from 1–5 (optional).', null=True)),
                ('title', models.CharField(blank=True, help_text='Short summary of the review (optional).', max_length=255)),
                ('comment', models.TextField(blank=True, help_text='Full review text / feedback from the client.')),
                ('is_published', models.BooleanField(default=False, help_text='If true, this review can be shown on website/marketing.')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When we responded to this review (optional).', null=True)),
                ('client', models.ForeignKey(help_text='Client who gave this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crm.client')),
                ('owner', models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, help_text='Team member who responded to this review (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_reviews_responded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
