# Generated by Django 5.2.7 on 2025-12-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_clientreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreview',
            name='is_published',
        ),
        migrations.AddField(
            model_name='clientreview',
            name='next_action',
            field=models.CharField(blank=True, help_text='Next follow-up action for this review (optional).', max_length=255),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='next_action_date',
            field=models.DateField(blank=True, help_text='Due date for next action (optional).', null=True),
        ),
    ]
