# Generated by Django 5.2.7 on 2025-12-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_clientreview_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='allow_marketing',
            field=models.BooleanField(default=True, help_text='Allow anniversary wishes, offers, and follow-up messages.'),
        ),
    ]
