# Generated by Django 5.2.7 on 2026-04-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_allow_marketing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='clientreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['client__name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='clientreview',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='clientreview',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='wedding_city',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='wedding_country',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='wedding_date',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='wedding_district',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='wedding_state',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.inquiry'),
        ),
        migrations.AlterField(
            model_name='client',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='next_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='allow_marketing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, choices=[('bride', 'Bride'), ('groom', 'Groom'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website Form'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('facebook', 'Facebook'), ('email', 'Email'), ('referral', 'Referral'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('lost', 'Lost'), ('converted', 'Converted')], default='new', max_length=50),
        ),
    ]
