# Generated by Django 5.2.7 on 2026-05-03 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_client_options_alter_clientreview_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientReview',
            new_name='Review',
        ),
    ]
