# Generated by Django 5.2.7 on 2026-05-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_rename_clientreview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='wedding_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='wedding_country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='wedding_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='wedding_state',
            field=models.CharField(blank=True, default='Kerala', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inquiries', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('converted_to_lead', 'Converted to Lead')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('lost', 'Lost'), ('converted_to_deal', 'Converted to Deal')], default='new', max_length=50),
        ),
    ]
