# Generated by Django 5.2.7 on 2025-11-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('installment', 'Installment / Partial'), ('final', 'Final'), ('refund', 'Refund'), ('other', 'Other')], default='advance', help_text='Whether this is advance, installment, final, etc.', max_length=32),
        ),
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sum of payments received (keep 0 if not using tax yet).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total tax amount (currently unused; set to 0).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Tax rate as percentage, e.g. 5.00 (0 for now).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Flat discount amount.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total tax amount (currently unused; set to 0).', max_digits=12),
        ),
    ]
