# Generated by Django 5.2.7 on 2025-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('installment', 'Installment / Partial'), ('final', 'Final'), ('refund', 'Refund'), ('other', 'Other')], default='advance', max_length=32),
        ),
    ]
