# Generated by Django 5.2.7 on 2025-11-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_payment_payment_type'),
        ('services', '0003_alter_package_currency_alter_package_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_items', to='services.package'),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
