# Generated by Django 5.2.7 on 2025-12-03 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_proposalitem_package_alter_proposalitem_description'),
        ('services', '0004_remove_package_currency_remove_service_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='proposal_item',
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, help_text='Internal contract number (auto-generated if left blank, e.g., CTR001).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected deal value (optional).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, help_text='Invoice number (auto-generated if blank).', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.contract')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_items', to='services.package')),
                ('proposal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_items', to='sales.proposalitem')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_items', to='services.service')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='contract_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='sales.contractitem'),
        ),
    ]
