# Generated by Django 5.2.7 on 2026-01-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_contract_owner_alter_deal_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='line_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, editable=False, help_text='Internal contract number (auto-generated e.g., CTR001).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, editable=False, help_text='Invoice number (auto-generated).', max_length=64, unique=True),
        ),
    ]
