# Generated by Django 5.2.7 on 2026-04-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_client_options_alter_clientreview_options_and_more'),
        ('sales', '0008_invoiceitem_line_subtotal_invoiceitem_tax_amount_and_more'),
        ('services', '0005_alter_inventoryitem_owner_alter_package_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contractitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='proposalitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.package'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
