# Generated by Django 5.2.7 on 2026-05-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_client_options_alter_clientreview_options_and_more'),
        ('sales', '0009_alter_contract_options_alter_contractitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.client'),
        ),
    ]
