# Generated by Django 5.2.7 on 2026-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_deal_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signing_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Secure public token used for client signing link.', null=True, unique=True),
        ),
    ]
