# Generated by Django 5.2.7 on 2026-05-26 16:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_populate_contract_signing_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalEventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['event_date', 'sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='contractitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='proposalitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='tax',
            new_name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='contractitem',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='proposalitem',
            name='proposal',
        ),
        migrations.AddField(
            model_name='contract',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ContractEventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_days', to='sales.contract')),
                ('proposal_event_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_event_days', to='sales.proposaleventday')),
            ],
            options={
                'ordering': ['event_date', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contractitem',
            name='contract_event_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.contracteventday'),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='event_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.proposaleventday'),
        ),
        migrations.CreateModel(
            name='ProposalItemDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(choices=[('item', 'Item'), ('hour', 'Hour'), ('day', 'Day'), ('photo', 'Photo'), ('video', 'Video'), ('album', 'Album'), ('page', 'Page'), ('minute', 'Minute'), ('other', 'Other')], default='item', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_included', models.BooleanField(default=True)),
                ('proposal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='sales.proposalitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(choices=[('item', 'Item'), ('hour', 'Hour'), ('day', 'Day'), ('photo', 'Photo'), ('video', 'Video'), ('album', 'Album'), ('page', 'Page'), ('minute', 'Minute'), ('other', 'Other')], default='item', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_included', models.BooleanField(default=True)),
                ('contract_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='sales.contractitem')),
                ('proposal_deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_deliverables', to='sales.proposalitemdeliverable')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, help_text='User who created or owns this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='sales.proposal')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='proposaleventday',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_days', to='sales.proposalplan'),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposal_plan',
            field=models.ForeignKey(blank=True, help_text='Accepted proposal plan copied into this contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='sales.proposalplan'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='accepted_plan',
            field=models.ForeignKey(blank=True, help_text='The final plan accepted by the client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_proposals', to='sales.proposalplan'),
        ),
        migrations.AddConstraint(
            model_name='proposalplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('proposal',), name='unique_primary_plan_per_proposal'),
        ),
        migrations.AddConstraint(
            model_name='proposalplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_accepted', True)), fields=('proposal',), name='unique_accepted_plan_per_proposal'),
        ),
    ]
